### PR TITLE
Java 9 Compilation

### PR DESCRIPTION
**Pull request by VoglSebastian**
This changes should fix compilation errors caused by Java 9. Also the attaching of a new Agent is refactored, since it did not work anymore if the project is compiled with Java 9.

### CODE REVIEW

**Comment by gofraser** [comment]
The build works with Java 11 now, but the tests fail. On the command line, I get:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project evosuite-runtime: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
```

Any idea?

**Comment by VoglSebastian** [comment]
> The build works with Java 11 now, but the tests fail. On the command line, I get:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project evosuite-runtime: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
> ```
> 
> Any idea?

Some tests are not compatible with the JRE 11 yet. I think most of the failures are caused by some older version of dependencies. Currently, i am working on finding those dependencies and updating them.

**Comment by gofraser** [comment]
You can find outdated dependencies with maven:

`mvn versions:display-dependency-updates`

Note that updating spring, hibernate, and all the J2EE stuff may break things so I'd avoid that if possible.

Updating mockito may also have some knock-on effects on the parts of EvoSuite that use it since it's a major version change.

**Comment by VoglSebastian** [comment]
> Note that updating spring, hibernate, and all the J2EE stuff may break things so I'd avoid that if possible.

I updated hibernate to 5.4.4, because according to the Compatibility Matrix of Hibernate
(https://hibernate.org/orm/releases/) the currently used version(5.2.13) is only compatible with java 8.

A command line execution of EvoSuite did not fail with either version (5.2.13 or 5.4.4). But some tests were failing with 5.2.13.

**Pull request merged**
