### PR TITLE
Fixed classloader construction for GenericClassImpl

### PR DESCRIPTION
**Pull request by henryhchchc**
Fixed the class not found issue arising when there are multiple elements in target class path.

### CODE REVIEW

**Comment by henryhchchc** [comment]
Closed due to impatience.

**Comment by henryhchchc** [comment]
The problem is that, when EvoSuite is launched with `-projectCP 'a.jar:b.jar:c.jar'`, the `URLClassLoader` in `GenericClassImpl` is constructed with **a single URL**, i.e., `new URL[] { "file://a.jar:b.jar:c.jar" }`, which does not point to any of the JAR files in the class path. In this case, `ClassNotFoundException` will be thrown even the class can be found in these JAR files.

To resolve the classes correctly, in this PR I split the class path with the path separator and construct the `URLClassLoader` with an array of URLs, i.e.,`new URL[]{ "file://a.jar", "file://b.jar", "file://c.jar" }`.

#428 might be due to this bug. The class cannot be found even the dependencies are specified in `-projectCP`.

**Comment by jose** [comment]
Thanks @henryhchchc.  I'm a bit confused though.  How have others (including mysefl) been successfully using EvoSuite with several dependencies in the `-projectCP` argument if, as you said

>  the URLClassLoader in GenericClassImpl is constructed with a single URL, i.e., new URL[] { "file://a.jar:b.jar:c.jar" }, which does not point to any of the JAR files in the class path.

**Comment by henryhchchc** [comment]
Please give me some time to construct an example to demonstrate the issue.

**Pull request closed without merging**
