### PR TITLE
MOSA Secondary Criteria

### PR DESCRIPTION
**Pull request by jose**
By default MOSA uses 'size' to distinguish two individuals with the same fitness value. This pull request makes MOSA use EvoSuite's secondary objective (which by default is also size).

@gofraser, can you please review this PR?

### CODE REVIEW

**Comment by gofraser** [comment]
Does the creation and evaluation of test suites negatively influence the performance of MOSA in the base case (branch coverage, secondary criterion only length)?

**Comment by jose** [comment]
I ran a quick experiment of the following configurations:

- A: MOSA default (branch coverage, secondary criterion length of test cases)
- B: the integration of EvoSuite's secondary objective proposed in this PR

on 339 classes (from the DynaMOSA study) and 100 repetitions.

| CovA | #GenA | CovB | #GenB | A12_CovA_vs_CovB | p_CovA_vs_CovB | A12_GenA_vs_GenB | p_GenA_vs_GenB |
| :---: | ---: | :---: | ---: | :---: | :---: | :---: | :---: |
| 0.62 | 196 | 0.61 | 166 | 0.55 | 0.23 | 0.63 | 0.22 |

Cov represents branch coverage achieved by each configuration, and Gen the number of generations of each configuration. Overall, the average branch coverage is pretty much the same for both configurations, 0.62 vs 0.61 (A12=0.55, and p-value=0.23). For the same search budget (60 seconds), configurations A seems to perform more generations than configuration B, 196 vs 166 (A12=0.63, p-value=0.22). This is a no surprise conclusion as the evaluation of test suites could take longer than the evaluation of single test cases, which could slow down the evolution.

A few more stats:

- For 124 out of 339 classes, A was better than B (Cov = 0.62 vs 0.60, A12=0.53, p-value=0.40)
- 78 classes, A was significantly better than B (Cov = 0.69 vs 0.69, A12=0.67, p-value=0.01)
- 46 classes, B was better than A (Cov = 0.83 vs 0.83, A12=0.48, p-value=0.55)
- 5 classes, B was significantly better than A (Cov = 0.71 vs 0.71, A12=0.42, p-value=0.03)
- 86 classes, both configurations performed equally

[(data.txt)](https://github.com/EvoSuite/evosuite/files/1543817/data.txt)

**Comment by gofraser** [comment]
Considering how difficult it is to achieve any improvement at all in terms of coverage, it seems that this negative effect might be something to take into account. Can't we simply make the sorting configurable?

**Comment by jose** [comment]
Currently, secondary objectives only work for **TestSuiteChromosome** objects, how about we implement secondary objectives with support for **TestChromosome**? This would make MOSA's secondary objective configurable and address the performance issue.

**Comment by gofraser** [comment]
Yes, sounds like an acceptable solution.

**Comment by jose** [comment]
@apanichella, could you please have a look at this PR and let us know what do you think?

**Comment by apanichella** [comment]
I'll give a look at it over the weekend. So I can do some trials on my laptop ;)

**Comment by jose** [comment]
Great. Thanks.

**Comment by apanichella** [comment]
Hi, I tried building EvoSuite (branch mosa_secondary_criteria) with maven but the build fails (test errors). I also tried with the master repo and got the same issue (even after cloning it as fresh repo from GitHub).

I also tried to run EvoSuite (same branch) with Eclipse using the following command 
`java -jar evosuite.jar -generateMOSuite -Dcriterion=BRANCH -Dalgorithm=MOSA -Dsearch_budget=60 -projectCP commons-lang3-3.3.2.jar  -class org.apache.commons.lang3.ClassUtils`. However, it crashes after few iteration with the following message: 

> ERROR org.evosuite.testcase.statements.FunctionalMockStatement - Failed to use Mockito on interface java.util.Comparator: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'java.util.Comparator', loaded by classloader : 'null'
  created class : 'codegen.java.util.Comparator$MockitoMock$1194347798', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@44bb34f8'
  proxy instance class : 'codegen.java.util.Comparator$MockitoMock$1194347798', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@44bb34f8'
  instance creation by : ObjenesisInstantiator

> You might experience classloading issues, please ask the mockito mailing-list.

> ERROR org.evosuite.testcase.execution.TestCaseExecutor - ExecutionException (this is likely a serious error in the framework)
java.util.concurrent.ExecutionException: org.evosuite.testcase.execution.EvosuiteError: org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'java.util.Comparator', loaded by classloader : 'null'
  created class : 'codegen.java.util.Comparator$MockitoMock$1194347798', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@44bb34f8'
  proxy instance class : 'codegen.java.util.Comparator$MockitoMock$1194347798', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@44bb34f8'
  instance creation by : ObjenesisInstantiator

EvoSuite (from my fork) works fine with the same configuration and same class/project.

**Comment by jose** [comment]
Hi @apanichella,

Yes, at the moment there are some test cases failing, but if you do

```
$ mvn clean package -DskipTests=true
```

you should be able to build it successfully.

Could you please:

1. report that FunctionalMockStatement error in the issue [tracker](https://github.com/EvoSuite/evosuite/issues)?
2. try mosa_secondary_criteria branch without EvoSuite's mocking (i.e., -Dmock_if_no_generator=false -D=functional_mocking_percent=1.0), as this PR does not depend on EvoSuite's mocking anyway.


--
Cheers,
Jose

**Comment by apanichella** [comment]
Right! It works with "-Dmock_if_no_generator=false -D=functional_mocking_percent=1.0"

**Comment by apanichella** [comment]
Hi, 
I run just a small experiment by comparing the size of the test suites (without applying the minimization process at the and of the search) generated by MOSA as implemented in the "master" branch and in the branch "Mosa_secondary_criteria". I used the following setting:
`java -jar evosuite.jar -generateMOSuite -Dcriterion=BRANCH -Dminimize=false -Dalgorithm=MOSA -Dsearch_budget=60 -projectCP commons-lang3-3.3.2.jar -class org.apache.commons.lang3.ClassUtils`.

The results that I got (20 runs for each implementation) are as follows:

Branch | Algorithm | Branc Cov. | Test Suite Size (# Statement)
--------|-----------|------------|-------------------------------
master | MOSA |  0.67 | 142.8
mosa_secondary_criteria | MOSA |  0.66 | 1572
-----

I spot a bug in how the archive is updated in MOSA. The following statement in the method `updateArchive` is incorrect: 
`if (existingSolution.compareSecondaryObjective(solution) < 0) {...`. 

It should be:
`// if the new solution is better (based on secondary criterion), then we need to update the archive`
`if (solution.compareSecondaryObjective(existingSolution) < 0) {...`

I tried to make a commit to fix this, but it seems that I don't have the rights to push my commits on the branch `mosa_secondary_criteria`

Anyhow, after this fix, the results become as follows:

Branch | Algorithm | Branc Cov. | Test Suite Size (# Statement)
--------|-----------|------------|-------------------------------
master | MOSA |  0.67 | 142.8
mosa_secondary_criteria | MOSA |  0.66 | 142.94
-----

The detailed results are in the attached file.
[statistics.txt](https://github.com/EvoSuite/evosuite/files/1707283/statistics.txt)

**Comment by jose** [comment]
Hi @apanichella,

Thanks for reviewing this and for running a few experiments.

> I run just a small experiment by comparing the size of the test suites (without applying the minimization process at the and of the search) generated by MOSA as implemented in the "master" branch and in the branch "Mosa_secondary_criteria". I used the following setting: `java -jar evosuite.jar -generateMOSuite -Dcriterion=BRANCH -Dminimize=false -Dalgorithm=MOSA -Dsearch_budget=60 -projectCP commons-lang3-3.3.2.jar -class org.apache.commons.lang3.ClassUtils.`

`mosa_secondary_criteria` is far behind master branch, so I'm not sure we can compare the coverage achieved by each one. (In case you want to repeat those experiments, I've just rebased this branch).

@apanichella, should I go ahead and merge it, or do you want to perform a few more experiments?

--
Best,
Jose

**Comment by apanichella** [comment]
Please go ahead with the merge! It looks fine to me.
I'll run few further experiments  but I would not expect any difference at this stage.

Annibale

**Comment by jose** [comment]
Great. Thank you.

@gofraser, can you please merge this?

**Pull request merged**
