### PR TITLE
Refactor MOSA's code

### PR DESCRIPTION
**Pull request by jose**
Hi,

To keep record of major changes, I decided to create a pull request to inform 1) what it has been done to clean up MOSA's code and to integrate EvoSuite's archive into MOSA, and 2) how does changes affect the overall performance of MOSA.

### Refactor

- The implementation of the NSGA-II and MOSA had loads of similar code which I removed the redundant bits, organised classes in the right packages, and refactored the code to handle both algorithms.
- The selection function for MOSA is now a parameter and not a pre-defined one.
- Moved some code from MOSA to AbstractMOSA class. (This will allow a much simpler integration of DynaMOSA, or even the development of other algorithms).
- Removed MOSA's ad hoc archive. This change was quite simple to perform due to recent changes I made, for example, updating EvoSuite's archive at test case level rather than at test suite level.
- Improved the performance of some MOSA's functions and their documentation.

### Performance

To assess whether this pull request negatively/positively affects the performance of MOSA, I ran two versions of EvoSuite on 344 classes and compared the coverage achieved by each version.

#### Setup

- 346 classes from the [DynaMOSA study](https://ieeexplore.ieee.org/abstract/document/7840029/) (note: two classes were excluded from my experiment due to an EvoSuite's limitation)
- Two versions of EvoSuite: (A) master branch; (B) this pull request.
- EvoSuite's default configuration
- 100 repetitions

#### Results

On average, both versions achieve an overall coverage of 72% (effect size 0.49, p-value 0.37). I.e., version (B) is slightly better than version (A), however not significantly better. Looking at class level, version (A) is significantly better than version (B) for 44 classes (coverage A 0.68 vs coverage B 0.67, effect size 0.63), and version (B) is significantly better than version (A) for 55 classes (coverage A 0.81 vs coverage B 0.84, effect size 0.30). Given these results, I would say it is safe to merge this pull request. (Please find attached the data and a R script to analyse that data)

@gofraser, any chance you could have a look at this and if there is not any comments approve this pull request?

--
Cheers,
Jose

[main.txt](https://github.com/EvoSuite/evosuite/files/1980400/main.txt)
[data.txt](https://github.com/EvoSuite/evosuite/files/1980404/data.txt)

### CODE REVIEW

**Comment by gofraser** [comment]
There's two failing tests in here (see circleci report).

Do you want to run this past @apanichella?

**Comment by apanichella** [comment]
Hi @gofraser and @jose, sure! I'll give a look at it later today or at latest tomorrow!

**Comment by jose** [comment]
Hi @apanichella, any chance you can review this PR soon?

--
Thanks,
Jose

**Comment by apanichella** [comment]
Hi @jose, I started the review but not finished yet. I'll complete it by today!

**Comment by apanichella** [comment]
I am checking the failing test right now and a general review. My commit will come soon

**Comment by apanichella** [comment]
Hi @jose and @gofraser,
the two test cases fail because there is an inconsistency between how the comparator for the (rank and) crowding distance is done and how the tests are made. 

To me, we should change the code of the comparison for the crowding distance. As implemented now, the crowding can be both maximized or minimized. However, this does not make much sense to me. The crowding distance (differently from the dominance) should be always maximized as it measures are diversified are the solutions within the same front. 

Does it make sense to minimize diversity in the front? For the dominance comparator, it is a different story: there we have to check whether the problem is a maximization or a minimization one to decide which test dominates the other.

If you agree with my point, I will change both code and tests for the crowding distance comparator.

**Comment by apanichella** [comment]
I made a pull request for the branch "mosa_archive" with the fixes for the crowding distance and one broken test case.  

I checked the remaining all other changes and the code looks good to me. Mainly, I checked:
1) the crowding distance, to be sure MOSA uses the fast version for many-objective optimization
2) the dominance comparator, which correctly applies the fast computation ass described in the TSE paper
4) the archive 
5) the progress monitor

All fine with me.  Once this pull request is accepted, I will add some test cases for the code related to MOSA.

Best,
Annibale

**Comment by gofraser** [comment]
Thanks Annibale. Should I wait merging Jose's PR until you've added your tests?

**Comment by apanichella** [comment]
I would say there is no need to wait. The refactoring already removed a lot of clones.
I will add tests in my spare time in the next days.

**Comment by gofraser** [comment]
OK thanks, I'll merge it. 

How does this affect the other to pull requests related to MOSA?

**Comment by apanichella** [comment]
For sure DynaMOSA needs to be updated with the latest EvoSuite code, like reusing the new archive (share with the other search strategies). I can take care of these changes and update the other pull requests

**Pull request merged**
